server:
  port: 9900

spring:

  application:
    name: tang-oms

  profiles:
    active: dev

  datasource:
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 5
      validation-query: SELECT 1 from dual
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      max-wait: 6000
      filter:
        wall,stat,slf4j

      tang-oms:
        url: jdbc:mysql://localhost:3306/tang_oms?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root123456
        driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 192.168.247.128
    #host: 192.168.68.128
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000

  kafka:
    bootstrap-servers: :localhost:9091,localhost:9092,localhost:9093
    security:
      protocol: PLAINTEXT
    consumer:
      enable-auto-commit: false
      auto-commit-interval: 5s
      auto-offset-reset: latest
      heartbeat-interval: 5s
      max-poll-records: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      autoStartup: true
      properties:
        # 5 * 1024 * 1024
        max.partition.fetch.bytes: 5242880
        #
        max.poll.interval: 600s
        session.timeout: 60s
        partition.assignmen.strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
        sasl:
          mechanism: PLAIN
          jaas:
            config: org.apache.kafka.common.security.scram.ScramLoginModule required username="" password="";

      isolation-level: read_committed
    producer:
      acks: -1
      properties:
        enable:
          idempotence: true
        sasl:
          mechanism: PLAIN
          jaas:
            config: org.apache.kafka.common.security.scram.ScramLoginModule required username="" password="";
      retries: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.tangv.feature: DEBUG
dubbo:
  application:
    name: tang-oms
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181

oss:
  access-key-id: LTAI5tMnjYswn8DfGy36LYew
  access-key-secret: pahvCgbdUVRLwIv5xwBz4LSVIW5lw2
