server:
  port: 9902

spring:
  profiles:
    active: dev

  application:
    name: tang-uaa

  datasource:
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 5
      validation-query: SELECT 1 from dual
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      max-wait: 6000
      filter:
        wall,stat,slf4j

      tang-uaa:
        url: jdbc:mysql://localhost:3306/tang_uaa?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root123456
        driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.tangv.feature: DEBUG
dubbo:
  application:
    name: tang-uaa
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
